/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log of VPN/Splunk actions */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Form options */
        get: operations["environments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs (QA: own only) */
        get: operations["listJobs"];
        put?: never;
        /** Submit an investigation */
        post: operations["submitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job detail and result */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Code trace chat */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the code trace chat */
        post: operations["closeTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask about the code trace */
        post: operations["askTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace/refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deployed commits and branches to re-trace into */
        get: operations["traceRefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen the code trace chat */
        post: operations["reopenTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/trace/retrace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trace the error in another version */
        post: operations["retrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace reports in KNOWLEDGE_DIR */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repos under GITLAB_REPOS_DIR and their rc sessions */
        get: operations["listRepos"];
        put?: never;
        /** Clone a GitLab project (in the background) */
        post: operations["cloneRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a Claude Remote Control session in a repo */
        post: operations["startRepoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/session/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a repo's Remote Control session */
        post: operations["stopRepoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/splunk/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start SSO re-auth (waits for 2FA in background) */
        post: operations["splunkReauth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/splunk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Splunk session state */
        get: operations["splunkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** VPN, Splunk and queue state with banners */
        get: operations["systemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MyTelkomsel support tools and their form fields */
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{tool}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a tool with the form values (400 bad input, 422 the tool refused) */
        post: operations["runTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claude subscription usage: 5-hour and weekly windows (refresh=1 re-probes) */
        get: operations["claudeUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/vpn/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the globalprotectcallback: URI */
        post: operations["vpnCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpn/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start GlobalProtect connect */
        post: operations["vpnConnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpn/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect GlobalProtect */
        post: operations["vpnDisconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpn/login-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SAML login link once captured */
        get: operations["vpnLoginURL"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpn/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redacted connect log */
        get: operations["vpnLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpn/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live VPN status */
        get: operations["vpnStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEntry: {
            action: string;
            /** Format: date-time */
            at: string;
            detail?: string;
            /** Format: int64 */
            id: number;
            result: string;
            /** Format: int64 */
            userId?: number | null;
            username?: string;
        };
        AuditListResponse: {
            entries: components["schemas"]["AuditEntry"][];
        };
        Banner: {
            /** @enum {string} */
            action?: "vpn" | "splunk";
            /** @enum {string} */
            level: "info" | "warning" | "error";
            message: string;
        };
        CallbackRequest: {
            uri: string;
        };
        CallbackResult: {
            /** Format: int64 */
            exitCode: number;
            /** @enum {string} */
            state: "IDLE" | "CONNECTING" | "WAITING_CALLBACK" | "SUBMITTING" | "CONNECTED" | "FAILED";
            stderr: string;
            stdout: string;
        };
        CmdResult: {
            /** Format: int64 */
            exitCode: number;
            stderr: string;
            stdout: string;
        };
        CodeTrace: {
            commit?: string;
            config?: components["schemas"]["ConfigVersion"] | null;
            deployJobUrl?: string;
            deployedAt?: string;
            env?: string;
            explanation?: string;
            file?: string;
            function?: string;
            /** Format: int64 */
            line?: number;
            model?: string;
            project?: string;
            reason?: string;
            ref?: string;
            refNote?: string;
            refSource?: string;
            snippet?: string;
            status: string;
            url?: string;
        };
        ConfigVersion: {
            branch?: string;
            commit?: string;
            deployJobUrl?: string;
            deployedAt?: string;
            env?: string;
            error?: string;
            note?: string;
            path?: string;
            project: string;
            source?: string;
            url?: string;
        };
        CreateUserRequest: {
            /** @description Menus a QA can open; omitted = all */
            menus?: ("investigasi" | "koneksi" | "laporan" | "tools")[];
            password: string;
            /** @enum {string} */
            role: "qa" | "engineer";
            username: string;
        };
        EnvironmentsResponse: {
            defaultTimeRange: string;
            environments: string[];
            timeRanges: string[];
            /** @description IANA zone for displaying times */
            timezone: string;
            /** @description Header carrying the transaction ID in a pasted curl */
            transactionIdHeader: string;
        };
        ErrorBody: {
            code?: string;
            error: string;
        };
        HealthResponse: {
            db: boolean;
            ok: boolean;
            splunkOk: boolean;
            vpnHealthy: boolean;
        };
        Job: {
            /** Format: date-time */
            analyzedAt?: string | null;
            environment: string;
            failureReason?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            inputKind: "transaction_id" | "curl";
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            searchDoneAt?: string | null;
            sprintIdentifier?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** @enum {string} */
            status: "QUEUED" | "CHECKING_VPN" | "SEARCHING" | "ANALYZING" | "WAITING_VPN" | "WAITING_SPLUNK" | "DONE" | "NO_LOGS" | "FAILED" | "CANCELLED" | "EXPIRED";
            timeRange: string;
            transactionId: string;
            /** Format: int64 */
            userId: number;
            username: string;
            /** Format: date-time */
            vpnCheckedAt?: string | null;
            /** Format: date-time */
            waitingSince?: string | null;
        };
        JobListResponse: {
            jobs: components["schemas"]["Job"][];
        };
        JobView: {
            /** Format: date-time */
            analyzedAt?: string | null;
            environment: string;
            failureReason?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            inputKind: "transaction_id" | "curl";
            /**
             * Format: int64
             * @description Jobs ahead of this one while it is pending
             */
            queuePosition?: number | null;
            /** Format: date-time */
            queuedAt: string;
            result?: components["schemas"]["Result"] | null;
            /** Format: date-time */
            searchDoneAt?: string | null;
            sprintIdentifier?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** @enum {string} */
            status: "QUEUED" | "CHECKING_VPN" | "SEARCHING" | "ANALYZING" | "WAITING_VPN" | "WAITING_SPLUNK" | "DONE" | "NO_LOGS" | "FAILED" | "CANCELLED" | "EXPIRED";
            timeRange: string;
            transactionId: string;
            /** Format: int64 */
            userId: number;
            username: string;
            /** Format: date-time */
            vpnCheckedAt?: string | null;
            /** Format: date-time */
            waitingSince?: string | null;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginURLResponse: {
            /** @enum {string} */
            state: "IDLE" | "CONNECTING" | "WAITING_CALLBACK" | "SUBMITTING" | "CONNECTED" | "FAILED";
            /** @description /saml-login or an https URL; null until captured */
            url?: string | null;
        };
        LogsResponse: {
            lines: string[];
        };
        OKResponse: {
            ok: boolean;
        };
        QueueSummary: {
            /** Format: int64 */
            active: number;
            /** Format: int64 */
            max: number;
        };
        ReachResult: {
            error?: string;
            host: string;
            ok: boolean;
        };
        RepoCloneView: {
            by: string;
            error?: string;
            project: string;
            /** Format: date-time */
            startedAt: string;
            /** @enum {string} */
            state: "cloning" | "failed";
        };
        RepoRequest: {
            project: string;
        };
        RepoSessionResponse: {
            /** @description What the rc-session script reported */
            output: string;
            repo: components["schemas"]["RepoView"];
        };
        RepoSessionView: {
            /** @description tmux session name */
            name: string;
            /** Format: date-time */
            since: string;
            /** @description claude.ai link once connected */
            url?: string;
        };
        RepoView: {
            /** @description Empty when HEAD is detached (a tracer store) */
            branch?: string;
            commit?: string;
            /** Format: date-time */
            committedAt?: string | null;
            project: string;
            session?: components["schemas"]["RepoSessionView"] | null;
            shallow: boolean;
            subject?: string;
        };
        ReportView: {
            date?: string;
            endpoints: string[];
            hasHtml: boolean;
            /** @description Always false for QA */
            hasMd: boolean;
            repo: string;
            severity?: string;
            slug: string;
            status?: string;
            summary?: string;
            tags: string[];
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReportsResponse: {
            /** @description Engineers read report.md and download the vault zip */
            canReadMd: boolean;
            reports: components["schemas"]["ReportView"][];
        };
        ReposResponse: {
            /** @description GitLab URL and token are set */
            canClone: boolean;
            /** @description The rc-session script is installed */
            canSession: boolean;
            /** @description Clones running or failed since the server started */
            clones: components["schemas"]["RepoCloneView"][];
            /** @description Group of a project given without one */
            defaultGroup: string;
            repos: components["schemas"]["RepoView"][];
        };
        Result: {
            codeTrace?: components["schemas"]["CodeTrace"] | null;
            /** @enum {string} */
            errorSource?: "esb" | "tibco" | "internal" | "unknown";
            errorType?: string;
            failedComponent?: string;
            likelyCause?: string;
            linkedIds?: string[];
            llmFailed: boolean;
            model?: string;
            pods?: string[];
            qaMessage?: string;
            rawLogSnippet?: string;
            relevantLogs?: string[];
            /** @enum {string} */
            severity?: "low" | "medium" | "high" | "critical";
            sourceLabel?: string;
            sprintIdentifier?: string;
            suggestedAction?: string;
            summary?: string;
        };
        SessionInfo: {
            /** Format: date-time */
            lastReauthAt?: string | null;
            lastReauthLog?: string[];
            lastReauthOk?: boolean | null;
            loaded: boolean;
            missingCookies?: string[];
            reauthRunning: boolean;
            /** Format: date-time */
            savedAt?: string | null;
        };
        SessionResponse: {
            /** @description Send as X-CSRF-Token on POST/PATCH */
            csrfToken: string;
            user: components["schemas"]["User"];
        };
        Snapshot: {
            /** Format: date-time */
            checkedAt: string;
            fiveHour?: components["schemas"]["Window"] | null;
            sevenDay?: components["schemas"]["Window"] | null;
            /** @description allowed, allowed_warning or rejected */
            status: string;
        };
        SplunkSummary: {
            /** Format: date-time */
            checkedAt: string;
            detail?: string;
            ok: boolean;
            paused: boolean;
            reauthing: boolean;
            session: components["schemas"]["SessionInfo"];
        };
        StatusResult: {
            connectAlive: boolean;
            /** Format: date-time */
            connectedAt?: string | null;
            connectedBy?: string;
            gpStatus: string;
            healthy: boolean;
            iface: string[];
            operator?: string;
            reach: components["schemas"]["ReachResult"][];
            /** @enum {string} */
            state: "IDLE" | "CONNECTING" | "WAITING_CALLBACK" | "SUBMITTING" | "CONNECTED" | "FAILED";
        };
        SubmitJobRequest: {
            environment: string;
            /** @description Run again even if a result from the last 24h exists */
            force?: boolean;
            /** @description Transaction ID or full curl command */
            input: string;
            /** @enum {string} */
            timeRange: "24h" | "48h";
        };
        SubmitJobResponse: {
            duplicate: boolean;
            job: components["schemas"]["JobView"];
        };
        SystemStatus: {
            banners: components["schemas"]["Banner"][];
            queue: components["schemas"]["QueueSummary"];
            splunk: components["schemas"]["SplunkSummary"];
            vpn: components["schemas"]["VPNSummary"];
        };
        ToolField: {
            default: string;
            group: string;
            help: string;
            label: string;
            name: string;
            options?: components["schemas"]["ToolOption"][];
            placeholder: string;
            required: boolean;
            showIf?: components["schemas"]["ToolShowIf"] | null;
            /** @enum {string} */
            type: "text" | "textarea" | "select" | "tabs" | "number" | "checkbox";
        };
        ToolInfo: {
            description: string;
            docs: string;
            fields: components["schemas"]["ToolField"][];
            id: string;
            name: string;
        };
        ToolOption: {
            label: string;
            value: string;
        };
        ToolOutput: {
            /** @enum {string} */
            kind: "code" | "link";
            label: string;
            value: string;
        };
        ToolResult: {
            outputs: components["schemas"]["ToolOutput"][];
            summary: components["schemas"]["ToolSummaryItem"][];
            warnings: string[];
        };
        ToolShowIf: {
            equals?: string;
            field: string;
            in?: string[];
        };
        ToolSummaryItem: {
            label: string;
            /** @description Hidden until revealed */
            secret?: boolean;
            value: string;
        };
        ToolsResponse: {
            tools: components["schemas"]["ToolInfo"][];
        };
        TraceAskRequest: {
            text: string;
        };
        TraceBranch: {
            commit: string;
            name: string;
        };
        TraceEnvDeployment: {
            commit?: string;
            env: string;
            error?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            ref?: string;
        };
        TraceMessage: {
            codeTrace?: components["schemas"]["CodeTrace"] | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            error?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: int64 */
            id: number;
            kind: string;
            model?: string;
            progress: string[];
            role: string;
            status: string;
            username?: string;
        };
        TraceRefsResponse: {
            branches: components["schemas"]["TraceBranch"][];
            deployments: components["schemas"]["TraceEnvDeployment"][];
        };
        TraceRepoView: {
            commit: string;
            env?: string;
            project: string;
            ref: string;
            /** @enum {string} */
            refSource: "deployed" | "fallback" | "manual";
        };
        TraceRetraceRequest: {
            env?: string;
            project: string;
            ref?: string;
        };
        TraceSessionView: {
            /** @description A question or re-trace is being answered */
            busy: boolean;
            /** @description GitLab environments offered for a re-trace */
            envs: string[];
            /** @description Closed because nobody wrote for idleMinutes */
            idleClosed: boolean;
            /** Format: int64 */
            idleMinutes: number;
            /** Format: date-time */
            lastActivityAt: string;
            messages: components["schemas"]["TraceMessage"][];
            /** @description Checkouts the session can read */
            repos: components["schemas"]["TraceRepoView"][];
            /**
             * @description open but idle sessions show as closed
             * @enum {string}
             */
            state: "open" | "closed" | "purged";
        };
        UpdateUserRequest: {
            active?: boolean | null;
            /** @description Replaces the menus a QA can open */
            menus?: ("investigasi" | "koneksi" | "laporan" | "tools")[] | null;
            password?: string | null;
            /** @enum {string|null} */
            role?: "qa" | "engineer" | null;
        };
        User: {
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            id: number;
            /** @description Menus this user can open; engineers always get all */
            menus: ("investigasi" | "koneksi" | "laporan" | "tools")[];
            /** @enum {string} */
            role: "qa" | "engineer";
            username: string;
        };
        UserListResponse: {
            users: components["schemas"]["User"][];
        };
        VPNStateResponse: {
            /** @enum {string} */
            state: "IDLE" | "CONNECTING" | "WAITING_CALLBACK" | "SUBMITTING" | "CONNECTED" | "FAILED";
        };
        VPNSummary: {
            /** Format: date-time */
            checkedAt: string;
            /** Format: date-time */
            connectedAt?: string | null;
            connectedBy?: string;
            detail?: string;
            healthy: boolean;
            /** @description User currently running a connect attempt */
            operator?: string;
            /** @enum {string} */
            state: "IDLE" | "CONNECTING" | "WAITING_CALLBACK" | "SUBMITTING" | "CONNECTED" | "FAILED";
        };
        Window: {
            /** @description Percent of the window used, 0-100 */
            percent: number;
            /** Format: date-time */
            resetsAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAudit: {
        parameters: {
            query?: {
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    environments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                environment?: string;
                status?: string;
                transactionId?: string;
                from?: string;
                to?: string;
                beforeId?: string;
                limit?: string;
                mine?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    submitJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitJobRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitJobResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitJobResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSessionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    closeTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSessionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    askTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceAskRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSessionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    traceRefs: {
        parameters: {
            query?: {
                project?: string;
                q?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceRefsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reopenTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSessionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    retrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceRetraceRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSessionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cloneRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoCloneView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    startRepoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSessionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stopRepoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSessionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    splunkReauth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplunkSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    splunkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplunkSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    systemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    runTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    claudeUsage: {
        parameters: {
            query?: {
                refresh?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallbackResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnConnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VPNStateResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnDisconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CmdResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnLoginURL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginURLResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    vpnStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
